Repository inclavare-containers/inclavare-containers, pull requests merged in 2020-12, with the labels that each got.

#366 .github/workflow: split jobs into separate ymls
  .github/workflows/rune_centos_with_docker_and_crictl.yml
  .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
Labels: epic, medium

#362 rune/libenclave: support new enclave type jailhouse
  rune/libenclave/check.go
  rune/libenclave/configs/config.go
  rune/libenclave/init.go
  rune/libenclave/jailhouse/device_linux.go
Labels: epic, medium, testing-before-checkin

#367 README.md: support pouch + pouchd + shim-rune + rune + enclave container images
  README.md
  docs/running_inclavare_containers_with_pouch_and_occlum.md
Labels: documentation, enhancement, testing-before-checkin

#374 ra-tls: enable debug build by default
  ra-tls/Makefile
  ra-tls/elv/ra-tls-client.c
  ra-tls/patch/wolfssl.patch
  ra-tls/ra-tls-server/lib/Makefile
  ra-tls/sgx-ra-tls/Makefile
  ra-tls/stub-enclave/Makefile
Labels: enhancement, medium

#377 docs/design: add CRI and runtime v2(shim API) in architecture.png
  docs/design/architecture.png
Labels: documentation, enhancement, testing-before-checkin

#378 README.md: document to declare that inclavare containers is added to the adopters list of containerd
  README.md
Labels: documentation, enhancement, testing-before-checkin

#385 epm: keep the communicating channel consistent between epm service an…
  epm/README-zh_CN.md
  epm/config/config_test.go
  epm/pkg/epm/enclave-cache-pool/enclavepool/enclave-cache.go
  rune/libenclave/epm/epm.go
  rune/libenclave/internal/runtime/pal/skeleton/README.md
Labels: bug, medium, testing-before-checkin

#382 .github/workflows: support k8s nightly build on centos
  .github/workflows/k8s_centos.yml
Labels: enhancement, medium

#386 README.md: occlum can run on non-flc machine with dcap driver
  patch/no-sgx-flc/README.md
Labels: documentation, enhancement

#390 inclavare-containers: ignore gnu global files
  .gitignore
Labels: enhancement, medium

#396 .github/workflow: support parallel jobs
  .github/workflows/rune_centos_with_docker_and_crictl.yml
  .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
Labels: bug, epic, gating, high

#399 .github/workflows: use make -j${coreNum} to replace make in rune
  .github/workflows/build_and_push_wamr_image.yml
  .github/workflows/k8s_centos.yml
  .github/workflows/repository_setup.yml
  .github/workflows/rune_centos_with_docker_and_crictl.yml
  .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
Labels: enhancement, medium

#389 rune/libenclave/skeleton: add max-mmap-size metadata area
  rune/libenclave/internal/runtime/pal/skeleton/README.md
  rune/libenclave/internal/runtime/pal/skeleton/arch.h
  rune/libenclave/internal/runtime/pal/skeleton/encl.c
  rune/libenclave/internal/runtime/pal/skeleton/encl.lds
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Labels: enhancement, epic, gating, high, testing-before-checkin

#406 .github/workflows: use the scratch image to replace centos to speed up docker build in CI/CD
  .github/workflows/rune_centos_with_docker_and_crictl.yml
  .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
Labels: enhancement, medium

#408 rune/libenclave/skeleton: add check for stdout and stderr in __pal_get_local_report
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
Labels: enhancement, medium, testing-before-checkin

#411 .github/workflows: add remote/local attestation CI/CD on ubuntu and centos
  .github/workflows/rune_centos_with_docker_and_crictl.yml
  .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
Labels: enhancement, medium

#412 .github/workflow: rename workflows
  .github/workflows/commit_centos.yml
  .github/workflows/commit_compile_check.yml
  .github/workflows/commit_ubuntu.yml
  .github/workflows/manually_crictl_image.yml
  .github/workflows/manually_repository_setup.yml
  .github/workflows/manually_wamr_image.yml
  .github/workflows/nightly.yml
Labels: enhancement, medium

#400 inclavared: fix subsequent tls client connection failures
  inclavared/Makefile.wolfssl
  inclavared/app.wolfssl/Makefile
  inclavared/app.wolfssl/src/main.rs
  inclavared/stub-enclave.wolfssl/Makefile
Labels: bug, gating, high

#413 README: add nightly build status badge
  README.md
Labels: documentation, enhancement, high

#409 .github/workflows: add clean network environment step in nightly build
  .github/workflows/nightly.yml
Labels: bug, gating, high

#414 rune/libenclave/skeleton: add xfrm and attribute metadate area
  rune/libenclave/internal/runtime/pal/skeleton/arch.h
  rune/libenclave/internal/runtime/pal/skeleton/encl.c
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Labels: epic, gating, high, testing-before-checkin

#417 .github/workflows: use pull_request_target instead of pull_request
  .github/workflows/commit_centos.yml
  .github/workflows/commit_ubuntu.yml
Labels: enhancement, medium

#420 ra-tls: rename enclaved to inclavared
  ra-tls/Makefile
  ra-tls/elv/main.go
  ra-tls/ra-tls-server/Makefile
  ra-tls/ra-tls-server/go.mod
  ra-tls/ra-tls-server/main.go
  ra-tls/ra-tls-server/run.go
Labels: epic, medium

#424 .github/workflows: add Occlum bundle test
  .github/workflows/commit_centos.yml
  .github/workflows/commit_ubuntu.yml
Labels: enhancement, medium

#422 rune/libenclave/skeleton: reformat cgo codes
  rune/libenclave/internal/runtime/pal/api_v1_linux.go
  rune/libenclave/internal/runtime/pal/api_v2_linux.go
  rune/libenclave/internal/runtime/pal/api_v3_linux.go
Labels: epic, medium, testing-before-checkin

#427 Makefile: enhance error handling when processing each component
  Makefile
Labels: enhancement, medium, testing-before-checkin

#430 .github/workflows: keep the test container when test fails
  .github/workflows/commit_centos.yml
  .github/workflows/commit_ubuntu.yml
Labels: bug, gating, high, testing-before-checkin

#421 rune/skeleton/README: refresh the README.md
  rune/libenclave/internal/runtime/pal/skeleton/README.md
Labels: documentation, gating, high, testing-before-checkin

#431 README.md: remove /var/run/epm configuration in config.json explicitly
  rune/libenclave/internal/runtime/pal/skeleton/README.md
Labels: documentation, epic, medium

#418 rune/libenclave/skeleton: add null_dereference_protection and mmap_min_addr to metadata area
  rune/libenclave/internal/runtime/pal/skeleton/arch.h
  rune/libenclave/internal/runtime/pal/skeleton/encl.c
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
  rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
Labels: epic, gating, high, testing-before-checkin

#432 rune/libenclave: make mount aesmd socket configurable
  rune/libenclave/check.go
Labels: epic, medium, testing-before-checkin

#436 .github/workflows: enhance nightly build
  .github/workflows/nightly.yml
Labels: enhancement, medium

#444 .github/workflows: clean the environment before nightly build
  .github/workflows/nightly.yml
Labels: high, testing-before-checkin, workaround

#446 .github/workflows: use make package to replace make binary on ubuntu CI/CD
  .github/workflows/commit_ubuntu.yml
Labels: enhancement, medium, testing-before-checkin

#442 rune/skeleton: allow to explicitely set attrs_mask and xfrm_mask in sigstruct
  rune/libenclave/internal/runtime/pal/skeleton/README.md
  rune/libenclave/internal/runtime/pal/skeleton/arch.h
  rune/libenclave/internal/runtime/pal/skeleton/defines.h
  rune/libenclave/internal/runtime/pal/skeleton/encl.c
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Labels: enhancement, medium, testing-before-checkin

#450 .github/workflows: reconstruct workflow
  .github/workflows/commit_centos.yml
  .github/workflows/commit_crictl.yml
  .github/workflows/commit_occlum.yml
  .github/workflows/commit_skeleton.yml
  .github/workflows/commit_ubuntu.yml
Labels: enhancement, high, testing-before-checkin

#455 .github/workflows: add SGX2 test support
  .github/workflows/commit_crictl.yml
  .github/workflows/commit_occlum.yml
  .github/workflows/commit_skeleton.yml
  .github/workflows/manually_repository_setup.yml
  .github/workflows/manually_wamr_image.yml
  .github/workflows/nightly.yml
Labels: enhancement, high

#454 sgx-tools/README.md: add declaration that not support DCAP driver until now
  sgx-tools/README.md
Labels: documentation, enhancement, medium, testing-before-checkin

#453 docs: add loglevel in pouch run command
  docs/running_inclavare_containers_with_pouch_and_occlum.md
Labels: documentation, enhancement, medium, testing-before-checkin

#457 .github/workflows: add semicolon after the command
  .github/workflows/commit_occlum.yml
Labels: bug, high

#458 rune/libenclave/skeleton/README.md: add declaration that not support DCAP driver until now for the rune attest command
  rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_rune_attest_command.md
Labels: documentation, medium, testing-before-checkin

#459 .github/workflows: workround occlum package dependency problem
  .github/workflows/nightly.yml
Labels: gating, high, workaround

#461 rune/libenclave/skeleton/README.md: add usage for skeleton with epm r…
  rune/libenclave/internal/runtime/pal/skeleton/README.md
Labels: documentation, low, testing-before-checkin

#456 .circleci: remove CircleCI config.yml
  .circleci/config.yml
  epm/.circleci/config.yml
  shim/.circleci/config.yml
Labels: enhancement, medium, testing-before-checkin

#460 inclavared: fix startup failure due to lack of tls socket
  inclavared/app.wolfssl/src/main.rs
Labels: bug, medium

#466 .github/workflows: add epm testing support
  .github/workflows/commit_epm.yml
Labels: enhancement, low

#468 epm: unify epm configuration path about epm.db and config.toml
  .github/workflows/commit_epm.yml
  epm/README.md
  epm/cmd/epm/app/options/options.go
  epm/conf/config.toml
  epm/config/config_test.go
Labels: bug, testing-before-checkin

#471 README: add nightly centos and ubuntu status badge
  README.md
Labels: documentation, high, testing-before-checkin

#476 README.md: simplify the description of the installation location of all components
  README.md
Labels: documentation, duplicate, medium

#477 .github/workflows: update the workflow of Nightly-Ubuntu-SGX1
  .github/workflows/nightly-ubuntu-sgx1.yml
Labels: epic, high, testing-before-checkin

#485 epm&shim: add the changelog of version 0.5.2 of shim and rune
  epm/dist/deb/debian/changelog
  epm/dist/rpm/epm.spec
  shim/dist/deb/debian/changelog
  shim/dist/rpm/shim-rune.spec
Labels: epic, gating, high, testing-before-checkin

#484 rune & sgx-tools: bump the versions of deb and rpm to 0.5.2
  rune/dist/deb/debian/changelog
  rune/dist/rpm/rune.spec
  sgx-tools/dist/deb/debian/changelog
  sgx-tools/dist/rpm/sgx-tools.spec
Labels: epic, gating, high, testing-before-checkin

#479 docs: add epm desgin document
  docs/design/epm/design.md
  docs/design/epm/epmclient.png
  docs/design/epm/epmservice.png
  docs/design/epm/getcache.png
  docs/design/epm/perftest.png
  docs/design/epm/savecache.png
Labels: documentation, epic, gating

#489 epm/README.md: add epm desgin reference link into epm README.md
  epm/README.md
Labels: documentation, enhancement

#490 rune: print the error message when --debug specified
  rune/init.go
Labels: enhancement, low, testing-before-checkin

#498 CONTRIBUTING.md: explicitly document writing CI/CD
  CONTRIBUTING.md
Labels: enhancement, medium

#501 .github/workflows: fix shelter test error
  .github/workflows/commit_shelter.yml
Labels: bug, gating, high

#503 Fix the typo encalvae
  rune/libenclave/epm/epm.go
  rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md
Labels: bug, medium, testing-before-checkin

#504 Bump the version to 0.5.2
  CHANGELOG
  VERSION
Labels: epic, gating, high
