Repository inclavare-containers/inclavare-containers, pull requests merged in 2020-11, with the labels that each got.

#320 rune/libenclave/skeleton: fix an issue about undefined symbol
  rune/libenclave/internal/runtime/pal/skeleton/Makefile
Labels: bug

#333 ra-tls: remove repeat file
  ra-tls/sgx-ra-tls/sgxsdk-ra-attester_u.c
Labels: bug

#336 CONTRIBUTING: update the description about fix line
  CONTRIBUTING.md
Labels: documentation, enhancement

#343 sgx-tools/dist: drop unnecessary dependency in rpm and deb
  sgx-tools/dist/deb/debian/changelog
  sgx-tools/dist/deb/debian/control
  sgx-tools/dist/deb/debian/rules
  sgx-tools/dist/rpm/sgx-tools.spec
Labels: enhancement, medium

#351 rune/libenclave: add enclave logLevel configuration
  rune/libenclave/check.go
  rune/libenclave/configs/config.go
  rune/libenclave/configs/log_level.go
  rune/libenclave/process_linux.go
  rune/libenclave/runelet.go
  rune/spec.go
Labels: enhancement, medium

#355 rune & sgx-tools: bump the versions of deb and rpm to 0.5.1
  rune/dist/deb/debian/changelog
  rune/dist/deb/debian/control
  rune/dist/rpm/rune.spec
  sgx-tools/dist/deb/debian/changelog
  sgx-tools/dist/rpm/sgx-tools.spec
Labels: epic, gating, high

#357 rune/libenclave/nitro_enclaves: add a base support for aws sample nitro enclave
  rune/libenclave/internal/runtime/pal/nitro_enclaves/Makefile
  rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md
  rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.c
  rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.h
  rune/libenclave/internal/runtime/pal/nitro_enclaves/nitro_enclaves.h
  rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c
  rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.h
Labels: epic, medium

#358 epm: add subType field to epm add health interface to enclave pool
  epm/cmd/epm/app/server.go
  epm/dist/deb/debian/changelog
  epm/dist/rpm/epm.spec
  epm/pkg/epm-api/v1alpha1/api.pb.go
  epm/pkg/epm-api/v1alpha1/api.proto
  epm/pkg/epm/epm.go
  epm/pkg/epm/interface.go
  epm/pkg/metadata/metadata.go
  shim/dist/deb/debian/changelog
  shim/dist/rpm/shim-rune.spec
Labels: epic, medium
