Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-09, with the labels that each got.

#1359 rats-tls: set DT_LNK value to avoid compiling error under SGX mode
  rats-tls/src/attesters/internal/etls_enclave_attester_load_all.c
  rats-tls/src/crypto_wrappers/internal/etls_crypto_wrapper_load_all.c
  rats-tls/src/tls_wrappers/internal/etls_tls_wrapper_load_all.c
  rats-tls/src/verifiers/internal/etls_enclave_verifier_load_all.c
Labels: bug, high, testing-before-checkin

#1366 enclave-tls: solve a potential issue that -ldl -lc can't be found
  enclave-tls/rules/build_env.mk
Labels: bug, high

#1360 eaa: add CI/CD testing
  .github/workflows/pr_eaa.yml
Labels: blocked

#1357 avoid re-build intel-sgx-ssl and re-download openssl tarball
  rats-tls/cmake/SGXSSL.cmake
  rats-tls/src/external/sgx-ssl/patch/0001-add-ssl-library-enclave-support.patch
  rats-tls/src/external/sgx-ssl/patch/tcommon.h
  rats-tls/src/external/sgx-ssl/patch/tstdio.cpp
  rats-tls/src/external/sgx-ssl/patch/tunistd.cpp
Labels: bug, documentation, testing-before-checkin

#1370 rats-tls: introduce the new concept "session" in enclave tls API
  rats-tls/samples/rats-tls-server/server.c
  rats-tls/src/api/rats_tls_init.c
  rats-tls/src/api/rats_tls_negotiate.c
Labels: medium, testing-before-checkin

#1374 eaa: use env_log as verdictd & verdict info output mechanism
  eaa/verdict/Cargo.toml
  eaa/verdict/src/main.rs
  eaa/verdictd/Cargo.toml
  eaa/verdictd/src/attestation_agent/protocol.rs
  eaa/verdictd/src/attestation_agent/rats_tls.rs
  eaa/verdictd/src/configure_provider/provider.rs
  eaa/verdictd/src/key_manager/directory_key_manager.rs
  eaa/verdictd/src/key_provider/key_provider_grpc.rs
  eaa/verdictd/src/main.rs
  eaa/verdictd/src/policy_engine/opa/opa_engine.rs
  eaa/verdictd/src/rats_tls/mod.rs
Labels: testing-before-checkin
