Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-06, with the labels that each got.

#1090 inclavared: add third party dependencies to readme
  inclavared/README.md
Labels: documentation, medium

#1109 pal spec: fix typo
  rune/libenclave/internal/runtime/pal/spec.md
Labels: bug, documentation, medium

#1110 sgx-ecdsa: support to dump hash in quote
  enclave-tls/src/verifiers/sgx-ecdsa/verify_evidence.c
Labels: enhancement, medium

#1108 rune: fix the process name encoding error
  rune/libenclave/init_linux.go
Labels: bug, medium, testing-before-checkin

#1111 enclave-tls: Fix memory leak in enclave-tls-server
  enclave-tls/samples/enclave-tls-server/server.c
Labels: bug, medium, testing-before-checkin

#1127 hacks: add the sample tls cert generated by openssl instances
  enclave-tls/hacks/README.md
  enclave-tls/hacks/enclave-tls-cert-openssl-sample.pem
Labels: testing-before-checkin

#1147 enclave-tls/samples: set debug flag by default on enclave creation
  enclave-tls/README.md
  enclave-tls/samples/enclave-tls-client/client.c
  enclave-tls/samples/enclave-tls-server/server.c
Labels: testing-before-checkin

#1159 pr_shelter: stop the workflow when build shelter failure
  .github/workflows/pr_shelter.yml
Labels: testing-before-checkin

#1156 pr_crictl: enhance CI/CD error handling
  .github/workflows/pr_crictl.yml
Labels: testing-before-checkin

#1152 CI/CD: disable the enclave-tls openssl testing on alinux2
  .github/workflows/pr_enclave_tls.yml
  .github/workflows/pr_shelter.yml
Labels: testing-before-checkin

#1171 skeleton: clean up the description about enclave-tls
  rune/libenclave/internal/runtime/pal/skeleton/intergrate_skeleton_with_enclave_tls.md
Labels: testing-before-checkin

#1173 rune/skeleton: fix build failure due to wrong dependency to aesm.pb-c.c
  rune/libenclave/internal/runtime/pal/skeleton/Makefile
Labels: testing-before-checkin

#1174 tools/docker: clean up dockerfiles
  tools/docker/Dockerfile-inclavare-dev-alinux2
  tools/docker/Dockerfile-inclavare-dev-centos8.2
  tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
Labels: testing-before-checkin

#1162 enclave-tls: fix an issue about making etls package failure
  .github/workflows/pr_crictl.yml
  enclave-tls/dist/rpm/enclave_tls.filelist
  enclave-tls/dist/rpm/enclave_tls.spec
  enclave-tls/rules/build_env.mk
Labels: bug, high

#1183 inclavared: fix make package failure
  inclavared/Makefile
  inclavared/dist/deb/build.sh
  inclavared/dist/deb/debian/control
  inclavared/dist/deb/debian/rules
  inclavared/dist/rpm/inclavared.spec
Labels: testing-before-checkin

#1179 tools/docker: clean up aesm packages
  tools/docker/Dockerfile-inclavare-dev-alinux2
Labels: testing-before-checkin

#1176 docs: update sgx-tools README
  sgx-tools/README.md
Labels: testing-before-checkin

#1135 enclave-tls: remove hard code for ex_data index
  enclave-tls/src/tls_wrappers/openssl/Makefile
  enclave-tls/src/tls_wrappers/openssl/init.c
  enclave-tls/src/tls_wrappers/openssl/negotiate.c
  enclave-tls/src/tls_wrappers/openssl/per_thread.c
  enclave-tls/src/tls_wrappers/openssl/per_thread.h
  enclave-tls/src/tls_wrappers/openssl/un_negotiate.c
Labels: bug, high, testing-before-checkin

#1188 enclave-tls: add debug mode
  enclave-tls/src/Makefile
Labels: testing-before-checkin

#1189 shelter: make package fails
  shelter/Makefile
  shelter/dist/deb/debian/control
  shelter/dist/rpm/shelter.spec
Labels: testing-before-checkin

#1190 rune: fix docker exec invalid argument problem
  rune/libenclave/agent.go
Labels: testing-before-checkin

#1191 enclave-tls: extract oid definition into a global header file
  enclave-tls/src/crypto_wrappers/openssl/gen_cert.c
  enclave-tls/src/include/enclave-tls/oid.h
  enclave-tls/src/tls_wrappers/openssl/openssl.h
  enclave-tls/src/tls_wrappers/openssl/un_negotiate.c
Labels: enhancement, high, testing-before-checkin

#1192 shelter/dist: fix make package error in ubuntu
  shelter/dist/deb/debian/rules
Labels: testing-before-checkin

#1193 cicd: fix nightly cicd bugs
  .github/workflows/nightly-aliyunlinux-sgx2.yml
  .github/workflows/nightly-centos-sgx1.yml
  .github/workflows/nightly-ubuntu-sgx1.yml
  .github/workflows/pr_occlum.yml
Labels: testing-before-checkin

#1197 enclave-tls/docs: refresh docs
  enclave-tls/docs/run_enclave_tls_with_occlum.md
  enclave-tls/docs/run_inclavared_and_shelter_with_enclave_tls.md
Labels: testing-before-checkin

#1200 enclave-tls: Fix the issue of OBJ creation failure
  enclave-tls/src/crypto_wrappers/openssl/gen_cert.c
Labels: bug, high, testing-before-checkin

#1198 pr_crictl: fix StartContainerResponse of containerd return nil and use make-packages action
  .github/actions/make-packages/action.yml
  .github/workflows/pr_crictl.yml
Labels: testing-before-checkin

#1207 enclave-tls: shutdown SSL session when TLS cleanup
  enclave-tls/src/tls_wrappers/openssl/cleanup.c
Labels: bug, medium, testing-before-checkin

#1208 rune & sgx-tools: bump the versions of deb and rpm to 0.6.2
  rune/dist/deb/debian/changelog
  rune/dist/rpm/rune.spec
  sgx-tools/dist/deb/debian/changelog
  sgx-tools/dist/rpm/sgx-tools.spec
Labels: testing-before-checkin

#1213 enclave-tls & epm: bump the version of deb and rpm to 0.6.2
  enclave-tls/dist/deb/debian/changelog
  enclave-tls/dist/rpm/enclave_tls.spec
  epm/dist/deb/debian/changelog
  epm/dist/rpm/epm.spec
Labels: enhancement, medium
