Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-02, with the labels that each got.

#597 rune/libenclave/epm: fix a bug about sgx mmap failure
  rune/libenclave/epm/cmsg.go
  rune/libenclave/epm/epm.go
Labels: bug, medium, testing-before-checkin

#596 rune/libenclave/intelsgx && attestation: both support quote version 2 and version 3
  rune/libenclave/attestation/sgx/ias/ias.go
  rune/libenclave/intelsgx/aesmd.go
  rune/libenclave/intelsgx/arch.go
Labels: enhancement, medium, no-cicd, testing-before-checkin

#598 shelter: correct the typo "encalve" to "enclave"
  shelter/mrenclaveverifycomand.go
  shelter/racommand.go
  shelter/remoteattestation/securitychannel.go
  shelter/verification/Makefile
  shelter/verification/mrenclave.go
Labels: bug, epic, medium, testing-before-checkin

#601 rune/libenclave/attestation: fix the return error of the sgxEpidChallenger.New function
  rune/libenclave/attestation/sgx-epid-challenger.go
Labels: bug, high, testing-before-checkin

#602 skeleton: integrate the latest stable wolfssl with DCAP support
  ra-tls/ra-tls-server/lib/Makefile
  rune/libenclave/intelsgx/preload/device_linux.go
  rune/libenclave/internal/runtime/pal/skeleton/Makefile
  rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
Labels: epic, gating, high, no-cicd, testing-before-checkin

#605 rune/skeleton: fix EINIT rc 8 failure on SGX2 platforms
  rune/libenclave/internal/runtime/pal/skeleton/sgx.h
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
  rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
Labels: bug, high, testing-before-checkin

#606 rune/libenclave/attestation: move sgx-epid-challenger.go to the sgx/sgx_challenger package
  rune/libenclave/attestation/challenger.go
  rune/libenclave/attestation/sgx/sgx_challenger/sgx-epid-challenger.go
  rune/libenclave/internal/runtime/pal/pal_linux.go
Labels: enhancement, medium, testing-before-checkin

#607 rune & sgx-tools: bump the versions of deb and rpm to 0.6.0
  rune/dist/deb/debian/changelog
  rune/dist/rpm/rune.spec
  sgx-tools/dist/deb/debian/changelog
  sgx-tools/dist/rpm/sgx-tools.spec
Labels: epic, gating, medium, no-cicd

#610 shim & epm: update the spec files of shim and epm
  epm/dist/deb/debian/changelog
  epm/dist/rpm/epm.spec
  shim/dist/deb/debian/changelog
  shim/dist/rpm/shim-rune.spec
Labels: epic, gating, medium

#622 skeleton/running_skeleton_with_tls_server.md: fix the url error
  rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
Labels: bug, documentation, medium

#623 ra-tls: typo fix for ra-tls-client
  ra-tls/elv/ra-tls-client.c
Labels: bug, medium, testing-before-checkin

#628 rune/skeleton: integrate the latest ra-tls with local report attestation support
  rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
Labels: epic, gating, high, no-cicd, testing-before-checkin

#629 CI/CD: add glibc static dependency needed by ra-tls
  .github/workflows/docker/Dockerfile-centos8.1
Labels: bug, high, testing-before-checkin

#633 CI/CD: install libsgx-headers*.deb in Dockerfile-ubuntu18.04
  .github/workflows/docker/Dockerfile-ubuntu18.04
Labels: enhancement, medium

#641 skeleton/sgxsign: fix EINIT failure dueto SGX_INVALID_SIGNATURE
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Labels: bug, gating, high, testing-before-checkin

#640 CI/CD: in the Dockerfile-ubuntu18.04, use soft link instead of installing libsgx-headers to compile rune
  .github/workflows/docker/Dockerfile-ubuntu18.04
Labels: bug, high

#643 skeleton/sgxsign: support to save SIGTRUCT for to-be-signed
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Labels: enhancement, medium, testing-before-checkin

#647 CI/CD: drop unnecessary soft link about sgx_attributes.h in Dockerfile-ubuntu18.04
  .github/workflows/docker/Dockerfile-ubuntu18.04
Labels: bug, medium

#646 skeleton/sgxsign: distinguish debug enclave from enclave debug
  rune/libenclave/internal/runtime/pal/skeleton/Makefile
  rune/libenclave/internal/runtime/pal/skeleton/README.md
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Labels: enhancement, medium, testing-before-checkin

#656 ra-tls/elv: fix failure on la report
  inclavared/app.wolfssl/Makefile
  inclavared/stub-enclave.wolfssl/Makefile
  ra-tls/elv/Makefile
  ra-tls/elv/echo-la.go
  ra-tls/elv/ra-tls-client.c
Labels: bug, high, testing-before-checkin

#665 Revert "CI/CD: drop unnecessary soft link about sgx_attributes.h in"
  .github/workflows/docker/Dockerfile-ubuntu18.04
Labels: enhancement, medium

#663 sgx-tools/dist/rpm: fix a typo
  sgx-tools/dist/rpm/sgx-tools.spec
Labels: enhancement, medium, testing-before-checkin
