Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-11, with the labels that each got.

#1446 rats-tls: compatible with openssl 1.0.x
  rats-tls/src/include/rats-tls/api.h
  rats-tls/src/tls_wrappers/openssl/CMakeLists.txt
  rats-tls/src/tls_wrappers/openssl/init.c
  rats-tls/src/tls_wrappers/openssl/openssl.h
  rats-tls/src/tls_wrappers/openssl/un_negotiate.c
  rats-tls/src/tls_wrappers/openssl/use_cert.c
  rats-tls/src/tls_wrappers/openssl/x509_openssl10x.c
Labels: testing-before-checkin

#1452 rats-tls/tdx: add the tdx capability check in tdx_attester_pre_init()
  .clang-format
  rats-tls/src/attesters/tdx/pre_init.c
  rats-tls/src/core/cpu.c
  rats-tls/src/include/internal/cpu.h
  rats-tls/src/include/rats-tls/err.h
Labels: testing-before-checkin, rfc

#1458 rats-tls: fatal error: openssl/opensslv.h: No such file or directory
  rats-tls/CMakeLists.txt
  rats-tls/samples/sgx-stub-enclave/CMakeLists.txt
  rats-tls/src/CMakeLists.txt
  rats-tls/src/attesters/nullattester/CMakeLists.txt
  rats-tls/src/attesters/sgx-ecdsa/CMakeLists.txt
  rats-tls/src/attesters/sgx-la/CMakeLists.txt
  rats-tls/src/crypto_wrappers/nullcrypto/CMakeLists.txt
  rats-tls/src/crypto_wrappers/openssl/CMakeLists.txt
  rats-tls/src/external/sgx-ssl/CMakeLists.txt
  rats-tls/src/sgx/trust/CMakeLists.txt
  rats-tls/src/tls_wrappers/nulltls/CMakeLists.txt
  rats-tls/src/tls_wrappers/openssl/CMakeLists.txt
  rats-tls/src/verifiers/nullverifier/CMakeLists.txt
  rats-tls/src/verifiers/sgx-ecdsa-qve/CMakeLists.txt
  rats-tls/src/verifiers/sgx-ecdsa/CMakeLists.txt
  rats-tls/src/verifiers/sgx-la/CMakeLists.txt
Labels: bug, testing-before-checkin

#1470 CONTRIBUTING.md: add the step to install clang-format for CentOS8
  CONTRIBUTING.md
Labels: testing-before-checkin

#1471 rats-tls: fix auto-selection sgx_ecdsa verifier in non-sgx platform
  rats-tls/src/core/cpu.c
  rats-tls/src/include/internal/cpu.h
  rats-tls/src/include/rats-tls/verifier.h
  rats-tls/src/verifiers/api/enclave_verifier_register.c
  rats-tls/src/verifiers/sgx-ecdsa-qve/main.c
  rats-tls/src/verifiers/sgx-ecdsa/main.c
  rats-tls/src/verifiers/sgx-la/main.c
Labels: testing-before-checkin

#1480 rats-tls: rename ENCLAVE_VERIFIER_FLAGS_DEFAULT to ENCLAVE_VERIFIER_O…
  rats-tls/src/include/rats-tls/verifier.h
  rats-tls/src/verifiers/nullverifier/main.c
  rats-tls/src/verifiers/sgx-ecdsa-qve/main.c
  rats-tls/src/verifiers/sgx-ecdsa/main.c
  rats-tls/src/verifiers/sgx-la/main.c
Labels: testing-before-checkin

#1482 rats-tls: change "Rats TLS" in the banner info to "RATS-TLS"
  rats-tls/samples/rats-tls-client/client.c
  rats-tls/samples/rats-tls-server/server.c
  rats-tls/samples/sgx-stub-enclave/sgx_stub_ecall.c
Labels: testing-before-checkin

#1478 rats-tls: in sgx mode build will failed without libsgx-tsgx-ssl.a
  rats-tls/cmake/SGXSSL.cmake
Labels: bug

#1494 enclave-tls: use VERSION file as the package version when running mak…
  enclave-tls/.gitignore
  enclave-tls/MAINTAINERS
  enclave-tls/Makefile
  enclave-tls/VERSION
  enclave-tls/dist/Makefile
  enclave-tls/dist/deb/build.sh
  enclave-tls/dist/deb/debian/changelog.in
  enclave-tls/dist/rpm/enclave_tls.spec.in
Labels: gating

#1472 epm: use VERSION file as the package version when running make package
  epm/.gitignore
  epm/MAINTAINERS
  epm/Makefile
  epm/VERSION
  epm/dist/Makefile
  epm/dist/deb/build.sh
  epm/dist/deb/debian/changelog.in
  epm/dist/rpm/epm.spec.in
Labels: low, gating, epic, testing-before-checkin

#1493 CI/CD：rats-tls build failure due to sys/stat.h: No such file or directory in sgx mode
  rats-tls/src/core/cpu.c
  rats-tls/src/include/edl/rtls_syscalls.edl
  rats-tls/src/include/internal/cpu.h
  rats-tls/src/sgx/untrust/rtls_syscalls_ocall.c
Labels: testing-before-checkin

#1509 rats-tls: use VERSION file as the package version when running make p…
  rats-tls/.gitignore
  rats-tls/MAINTAINERS
  rats-tls/Makefile
  rats-tls/VERSION
  rats-tls/dist/Makefile
  rats-tls/dist/deb/build.sh
  rats-tls/dist/deb/debian/changelog.in
  rats-tls/dist/deb/debian/control
  rats-tls/dist/deb/debian/rules
  rats-tls/dist/rpm/rats_tls.spec.in
Labels: low, gating
