Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-08, with the labels that each got.

#1295 rats-tls: sovle compilation error under openssl1.0.x env
  rats-tls/src/crypto_wrappers/openssl/openssl.h
Labels: high, gating, blocked

#1298 rats-tls: add user callback for OPA
  rats-tls/samples/enclave-tls-client/client.c
  rats-tls/samples/enclave-tls-server/server.c
  rats-tls/samples/sgx-stub-enclave/sgx_stub_ecall.c
  rats-tls/src/CMakeLists.txt
  rats-tls/src/api/enclave_tls_callback.c
  rats-tls/src/include/enclave-tls/api.h
  rats-tls/src/include/internal/core.h
  rats-tls/src/tls_wrappers/openssl/un_negotiate.c
Labels: high, gating, testing-before-checkin

#1307 pr_occlum: use start-docker-daemon action to start docker
  .github/workflows/pr_occlum.yml
Labels: testing-before-checkin

#1337 docs: move enclave-tls design docs to rats-tls and enclave-tls sepera…
  enclave-tls/docs/designdocs/architecture.png
  enclave-tls/docs/designdocs/design-zh.md
  enclave-tls/docs/designdocs/design.md
  enclave-tls/docs/designdocs/enclave_tls_cleanup.png
  enclave-tls/docs/designdocs/enclave_tls_init.png
  enclave-tls/docs/designdocs/enclave_tls_negotiate.png
  enclave-tls/docs/designdocs/enclave_tls_transmite.png
  enclave-tls/docs/designdocs/initialization.png
  enclave-tls/docs/designdocs/mutual_attestation.png
  enclave-tls/docs/designdocs/x509.png
  enclave-tls/docs/run_inclavared_and_shelter_with_enclave_tls.md
  rats-tls/docs/designdocs/architecture.png
  rats-tls/docs/designdocs/design-zh.md
  rats-tls/docs/designdocs/design.md
  rats-tls/docs/designdocs/enclave_tls_cleanup.png
  rats-tls/docs/designdocs/enclave_tls_init.png
  rats-tls/docs/designdocs/enclave_tls_negotiate.png
  rats-tls/docs/designdocs/enclave_tls_transmite.png
  rats-tls/docs/designdocs/initialization.png
  rats-tls/docs/designdocs/mutual_attestation.png
  rats-tls/docs/designdocs/x509.png
Labels: documentation
