Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-12, with the labels that each got.

#1517 enclave-tls: fix version number does not start with digit error
  enclave-tls/dist/Makefile
Labels: bug, high, gating

#1519 verdictd: rename eaa to verdictd
  .github/workflows/pr_basic_compilation_check.yml
  .github/workflows/pr_verdictd.yml
  eaa/Cargo.toml
  eaa/verdict/Cargo.toml
  eaa/verdict/build.rs
  verdictd/Cargo.toml
  verdictd/Makefile
  verdictd/README.md
  verdictd/build.rs
  verdictd/cmd/verdict/readme.md
  verdictd/cmd/verdict/src/main.rs
  verdictd/docs/design/architecture.png
  verdictd/docs/design/design.md
  verdictd/docs/design/workprocess.png
  verdictd/proto/configureprovider.proto
  verdictd/proto/keyprovider.proto
  verdictd/src/attestation_agent/mod.rs
  verdictd/src/attestation_agent/protocol.rs
  verdictd/src/attestation_agent/rats_tls.rs
  verdictd/src/configure_provider/mod.rs
  verdictd/src/configure_provider/provider.rs
  verdictd/src/crypto/aes256_cbc.rs
  verdictd/src/crypto/aes256_gcm.rs
  verdictd/src/crypto/mod.rs
  verdictd/src/key_manager/directory_key_manager.rs
  verdictd/src/key_manager/mod.rs
  verdictd/src/key_provider/annotation.rs
  verdictd/src/key_provider/key_provider_grpc.rs
  verdictd/src/key_provider/messages.rs
  verdictd/src/key_provider/mod.rs
  verdictd/src/main.rs
  verdictd/src/policy_engine/mod.rs
  verdictd/src/policy_engine/opa/go.mod
  verdictd/src/policy_engine/opa/go.sum
  verdictd/src/policy_engine/opa/mod.rs
  verdictd/src/policy_engine/opa/opa_engine.go
  verdictd/src/policy_engine/opa/opa_engine.rs
  verdictd/src/policy_engine/opa/readme.md
  verdictd/src/rats_tls/ffi.rs
  verdictd/src/rats_tls/mod.rs
Labels: testing-before-checkin

#1528 rune: fix GHSA-v95c-p5hm-xq8f issue
  rune/Makefile
  rune/go.mod
  rune/go.sum
  rune/libenclave/container_linux.go
  rune/libenclave/rootfs_linux.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/hugetlb.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/dbus.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v1.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v2.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/message_linux.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
  rune/vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  rune/vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
  rune/vendor/modules.txt
Labels: testing-before-checkin

#1529 shim-rune: fix GHSA-v95c-p5hm-xq8f issue
  shim/go.mod
  shim/go.sum
  shim/vendor/github.com/bits-and-blooms/bitset/.gitignore
  shim/vendor/github.com/bits-and-blooms/bitset/.travis.yml
  shim/vendor/github.com/bits-and-blooms/bitset/LICENSE
  shim/vendor/github.com/bits-and-blooms/bitset/README.md
  shim/vendor/github.com/bits-and-blooms/bitset/azure-pipelines.yml
  shim/vendor/github.com/bits-and-blooms/bitset/bitset.go
  shim/vendor/github.com/bits-and-blooms/bitset/go.mod
  shim/vendor/github.com/bits-and-blooms/bitset/go.sum
  shim/vendor/github.com/bits-and-blooms/bitset/popcnt.go
  shim/vendor/github.com/bits-and-blooms/bitset/popcnt_19.go
  shim/vendor/github.com/bits-and-blooms/bitset/popcnt_amd64.go
  shim/vendor/github.com/bits-and-blooms/bitset/popcnt_amd64.s
  shim/vendor/github.com/bits-and-blooms/bitset/popcnt_generic.go
  shim/vendor/github.com/bits-and-blooms/bitset/trailing_zeros_18.go
  shim/vendor/github.com/bits-and-blooms/bitset/trailing_zeros_19.go
  shim/vendor/github.com/cilium/ebpf/CONTRIBUTING.md
  shim/vendor/github.com/cilium/ebpf/Makefile
  shim/vendor/github.com/cilium/ebpf/asm/func.go
  shim/vendor/github.com/cilium/ebpf/asm/func_string.go
  shim/vendor/github.com/cilium/ebpf/asm/instruction.go
  shim/vendor/github.com/cilium/ebpf/asm/load_store.go
  shim/vendor/github.com/cilium/ebpf/asm/opcode.go
  shim/vendor/github.com/cilium/ebpf/collection.go
  shim/vendor/github.com/cilium/ebpf/elf_reader.go
  shim/vendor/github.com/cilium/ebpf/internal/btf/btf.go
  shim/vendor/github.com/cilium/ebpf/internal/btf/btf_types.go
  shim/vendor/github.com/cilium/ebpf/internal/btf/btf_types_string.go
  shim/vendor/github.com/cilium/ebpf/internal/btf/core.go
  shim/vendor/github.com/cilium/ebpf/internal/btf/ext_info.go
  shim/vendor/github.com/cilium/ebpf/internal/btf/types.go
  shim/vendor/github.com/cilium/ebpf/internal/elf.go
  shim/vendor/github.com/cilium/ebpf/internal/endian.go
  shim/vendor/github.com/cilium/ebpf/internal/errors.go
  shim/vendor/github.com/cilium/ebpf/internal/ptr.go
  shim/vendor/github.com/cilium/ebpf/internal/syscall.go
  shim/vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  shim/vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  shim/vendor/github.com/cilium/ebpf/linker.go
  shim/vendor/github.com/cilium/ebpf/map.go
  shim/vendor/github.com/cilium/ebpf/prog.go
  shim/vendor/github.com/cilium/ebpf/run-tests.sh
  shim/vendor/github.com/cilium/ebpf/syscalls.go
  shim/vendor/github.com/cilium/ebpf/types.go
  shim/vendor/github.com/cilium/ebpf/types_string.go
  shim/vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  shim/vendor/github.com/opencontainers/selinux/go-selinux/doc.go
  shim/vendor/github.com/opencontainers/selinux/go-selinux/label/label_linux.go
  shim/vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
  shim/vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  shim/vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  shim/vendor/github.com/willf/bitset/go.mod
  shim/vendor/modules.txt
Labels: testing-before-checkin

#1527 Verdictd: Enhance OPA interfaces
  .github/workflows/pr_verdictd.yml
  verdictd/cmd/verdict/readme.md
  verdictd/cmd/verdict/src/main.rs
  verdictd/cmd/verdict/src/opa.rs
  verdictd/proto/configureprovider.proto
  verdictd/src/configure_provider/provider.rs
  verdictd/src/main.rs
  verdictd/src/policy_engine/opa/opa_engine.go
  verdictd/src/policy_engine/opa/opa_engine.rs
  verdictd/src/rats_tls/mod.rs
Labels: testing-before-checkin

#1526 ra-tls: fix verifier instance lost in verifier register
  rats-tls/src/verifiers/api/enclave_verifier_register.c
  rats-tls/src/verifiers/sgx-ecdsa-qve/main.c
  rats-tls/src/verifiers/sgx-ecdsa/main.c
  rats-tls/src/verifiers/sgx-la/main.c
Labels: bug, testing-before-checkin

#1530 Verdictd: add make package cmd
  .github/actions/make-packages/action.yml
  Makefile
  verdictd/MAINTAINERS
  verdictd/Makefile
  verdictd/VERSION
  verdictd/dist/Makefile
  verdictd/dist/deb/build.sh
  verdictd/dist/deb/debian/changelog.in
  verdictd/dist/deb/debian/compat
  verdictd/dist/deb/debian/control
  verdictd/dist/deb/debian/rules
  verdictd/dist/deb/debian/source/format
  verdictd/dist/rpm/verdictd.spec.in
Labels: testing-before-checkin

#1531 verdictd: switch cicd to make package cmd
  .github/actions/make-packages/action.yml
  .github/workflows/pr_verdictd.yml
  Makefile
  verdictd/dist/deb/debian/rules
  verdictd/dist/rpm/verdictd.spec.in
Labels: testing-before-checkin

#1536 dockerfile: add opa dependencies
  .github/actions/make-packages/action.yml
  .github/workflows/pr_verdictd.yml
  tools/docker/Dockerfile-inclavare-dev-alinux2
  tools/docker/Dockerfile-inclavare-dev-centos8.2
  tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
Labels: testing-before-checkin

#1538 rats-tls: support 'install' in sgx mode
  rats-tls/src/CMakeLists.txt
  rats-tls/src/attesters/nullattester/CMakeLists.txt
  rats-tls/src/attesters/sgx-ecdsa/CMakeLists.txt
  rats-tls/src/attesters/sgx-la/CMakeLists.txt
  rats-tls/src/crypto_wrappers/nullcrypto/CMakeLists.txt
  rats-tls/src/crypto_wrappers/openssl/CMakeLists.txt
  rats-tls/src/sgx/trust/CMakeLists.txt
  rats-tls/src/sgx/untrust/CMakeLists.txt
  rats-tls/src/tls_wrappers/nulltls/CMakeLists.txt
  rats-tls/src/tls_wrappers/openssl/CMakeLists.txt
  rats-tls/src/verifiers/nullverifier/CMakeLists.txt
  rats-tls/src/verifiers/sgx-ecdsa-qve/CMakeLists.txt
  rats-tls/src/verifiers/sgx-ecdsa/CMakeLists.txt
  rats-tls/src/verifiers/sgx-la/CMakeLists.txt
Labels: testing-before-checkin
