Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-01, with the labels that each got.

#508 docs: add OCCLUM_RELEASE_ENCLAVE env to explicitly set enclave mode
  docs/running_inclavare_containers_with_pouch_and_occlum.md
  rune/README.md
Labels: documentation, enhancement

#509 CI/CD: mask `command not found` error message
  .github/workflows/nightly-centos-sgx1.yml
  .github/workflows/nightly-ubuntu-sgx1.yml
Labels: enhancement, low

#511 CI/CD: touch .pb.go in vendor directories
  .github/workflows/commit_compile_check.yml
  .github/workflows/commit_epm.yml
  .github/workflows/commit_occlum.yml
  .github/workflows/commit_skeleton.yml
Labels: bug, high, testing-before-checkin

#510 CI/CD: update occlum version to 0.19.0 when nightly build
  .github/workflows/nightly-centos-sgx1.yml
  .github/workflows/nightly-ubuntu-sgx1.yml
Labels: enhancement, high, testing-before-checkin

#518 rune/skeleton: rename sgx_ecall to sgx_enclave_call
  rune/libenclave/internal/runtime/pal/skeleton/sgx_call.S
  rune/libenclave/internal/runtime/pal/skeleton/sgx_call.h
Labels: enhancement, medium, testing-before-checkin

#520 rune/skeleton: keep aesm.pb-c.c and aesm.pb-c.h in source code
  rune/libenclave/internal/runtime/pal/skeleton/.gitignore
  rune/libenclave/internal/runtime/pal/skeleton/Makefile
  rune/libenclave/internal/runtime/pal/skeleton/aesm.pb-c.c
  rune/libenclave/internal/runtime/pal/skeleton/aesm.pb-c.h
Labels: enhancement, high, testing-before-checkin

#522 CI/CD: extend the timeout value when creating pods
  .github/workflows/commit_crictl.yml
Labels: bug, high

#523 CI/CD: add dcap-related compile dependency in centos8.1 and ubuntu18.04
  .github/workflows/docker/Dockerfile-compile-check-centos8.1
  .github/workflows/docker/Dockerfile-compile-check-ubuntu18.04
Labels: enhancement, low

#524 rune: preload libsgx_epid.so
  rune/libenclave/intelsgx/preload/device_linux.go
Labels: bug, gating, high

#525 CI/CD: use the rune state command to check container status before doing remote attestation test
  .github/workflows/commit_skeleton.yml
Labels: enhancement, medium, testing-before-checkin

#529 rune/cli: adjust rune command according to lexicographic order
  rune/main.go
Labels: enhancement, low, testing-before-checkin

#545 CI/CD: fix the bug of failing to check the state of container for remote attestation testing
  .github/workflows/commit_skeleton.yml
Labels: bug, enhancement, gating, testing-before-checkin

#548 CI/CD: ingore the error print message when waiting for RA containers running.
  .github/workflows/commit_skeleton.yml
Labels: enhancement, gating, medium

#550 CI/CD: adjust the jobs order of get local report and get remote report.
  .github/workflows/commit_skeleton.yml
Labels: enhancement, medium

#517 rune/libenclave/skeleton: interactive with ra-tls-server
  rune/libenclave/internal/runtime/pal/skeleton/Makefile
  rune/libenclave/internal/runtime/pal/skeleton/README.md
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v3.c
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h
  rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
  rune/libenclave/internal/runtime/pal/skeleton/tls-server.c
  rune/libenclave/internal/runtime/pal/skeleton/tls-server.h
Labels: epic, gating, high, testing-before-checkin

#552 ra-tls: fix the bind address already in use problem
  ra-tls/ra-tls-server/run.go
Labels: enhancement, high

#556 CI/CD: add git proxy to speed up
  .github/workflows/commit_shelter.yml
Labels: enhancement, high

#553 rune/skeleton: add sanity check for exponent
  rune/libenclave/internal/runtime/pal/skeleton/arch.h
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Labels: enhancement, medium, testing-before-checkin

#557 CI/CD: workround skeleton occasionally failed problem
  .github/workflows/commit_skeleton.yml
Labels: high, testing-before-checkin, workaround

#558 rune/libenclave/skeleton: fix the bug of the inaccurate wait_timeout args
  rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
Labels: bug, gating, medium, testing-before-checkin

#559 ra-tls: rebase ra-tls sample code with the latest stable wolfssl
  ra-tls/Makefile
  ra-tls/patch/wolfssl.patch
  ra-tls/sgx-ra-tls/ra-challenger.c
  ra-tls/sgx-ra-tls/ra-challenger_private.h
  shelter/remoteattestation/ra-challenger.c
  shelter/remoteattestation/ra-challenger_private.h
Labels: epic, gating, high, testing-before-checkin

#561 CI/CD: use rune kill command to kill remote containers when all rune attest test completing
  .github/workflows/commit_skeleton.yml
Labels: enhancement, medium

#564 docs/k8s: add the ENCLAVE_RUNTIME_LOGLEVEL and OCCLUM_RELEASE_ENCLAVE environment variable to sync up with rune.
  docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md
Labels: documentation, enhancement, testing-before-checkin

#568 sgx-tools/Makefile: delete the non-existent proto dependency.
  sgx-tools/Makefile
Labels: enhancement, medium, testing-before-checkin

#580 hack/use-sbx-platform: support to verify the quote generated by SBX platforms
  hack/use-sbx-platform/0001-QVL-allow-to-use-SBX-platform.patch
  hack/use-sbx-platform/README.md
Labels: enhancement, medium

#583 rune/libenclave/intelsgx: implement ecdsa support for core APIs
  rune/libenclave/intelsgx/aesmd.go
  rune/libenclave/intelsgx/arch.go
  rune/libenclave/intelsgx/proto/aesm-service.pb.go
  rune/libenclave/intelsgx/proto/aesm-service.proto
Labels: enhancement, medium, testing-before-checkin

#587 rune/libenclave/intelsgx: make quote type related constant public
  rune/libenclave/intelsgx/aesmd.go
  rune/libenclave/intelsgx/arch.go
Labels: enhancement, medium, testing-before-checkin

#591 rune/skeleton: fix SGX_INVALID_SIGNATURE caused by sgxsign tool
  rune/libenclave/internal/runtime/pal/skeleton/arch.h
  rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Labels: bug, gating, medium, no-cicd, testing-before-checkin

#585 CI/CD: update sgx-tools testcases by add the quote type
  .github/workflows/commit_skeleton.yml
Labels: enhancement, medium

#593 CI/CD: revert the workround of skeleton failed problem
  .github/workflows/commit_skeleton.yml
Labels: high
