Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-04, with the labels that each got.

#759 rune: fix parsing sgx enclave device when using in-tree sgx driver
  rune/libenclave/check.go
Labels: bug, enhancement, high, testing-before-checkin

#774 rune: fix unable to mount sgx device pointing to the relative path
  rune/libenclave/check.go
Labels: testing-before-checkin

#793 enclave-tls: enable mutual attestation
  enclave-tls/README.md
  enclave-tls/samples/enclave-tls-client/client.c
  enclave-tls/samples/enclave-tls-server/server.c
  enclave-tls/src/tls_wrappers/wolfssl/negotiate.c
Labels: epic, gating, high

#797 README.md: add the explaination and pronunciation about inclavare
  README.md
Labels: documentation, gating, high

#800 rune/libenclave/epm: add support for sgx kernel driver upstreamed
  rune/libenclave/epm/procmaps.go
Labels: epic, high

#801 rune/libenclave/epm: fix a typo about pathname of SGX device node
  rune/libenclave/epm/procmaps.go
Labels: bug

#806 CI/CD: add compile check about enclave-tls
  .github/workflows/commit_compile_check.yml
  .github/workflows/docker/Dockerfile-compile-check-alinux2
  .github/workflows/docker/Dockerfile-compile-check-centos8.2
  .github/workflows/docker/Dockerfile-compile-check-ubuntu18.04
Labels: enhancement, high

#812 enclave-tls: add -std=c99 CFLAGS to fix gcc 4.8.5 compile error in alinux2
  enclave-tls/samples/enclave-tls-client/Makefile
Labels: bug, high

#820 enclave-tls/samples: fix return value error
  enclave-tls/samples/enclave-tls-client/client.c
  enclave-tls/samples/enclave-tls-server/server.c
Labels: testing-before-checkin

#818 enclave-tls: change sgx local attestation's verification mode
  enclave-tls/src/enclave_quotes/sgx-la/collect_evidence.c
  enclave-tls/src/enclave_quotes/sgx-la/ecalls.c
  enclave-tls/src/enclave_quotes/sgx-la/sgx_la.edl
  enclave-tls/src/enclave_quotes/sgx-la/verify_evidence.c
  enclave-tls/src/tls_wrappers/wolfssl-sgx/wolfssl_sgx.edl
Labels: bug, high, testing-before-checkin

#809 shelter: add rpm and deb spec for package build
  Makefile
  shelter/Makefile
  shelter/dist/Makefile
  shelter/dist/deb/build.sh
  shelter/dist/deb/debian/changelog
  shelter/dist/deb/debian/compat
  shelter/dist/deb/debian/control
  shelter/dist/deb/debian/rules
  shelter/dist/deb/debian/source/format
  shelter/dist/rpm/shelter.spec
Labels: testing-before-checkin

#833 enclave-tls/README.md: fix the dependent package name error in ubuntu 18.04
  enclave-tls/README.md
Labels: bug, documentation

#834 enclave-tls: refactor occlum and sgx sdk build
  enclave-tls/samples/enclave-tls-client/client.c
  enclave-tls/samples/enclave-tls-server/server.c
Labels: bug, medium, testing-before-checkin

#853 .github/workflows: make local attestation run on SGX2 machine only
  .github/workflows/commit_enclave_tls.yml
Labels: bug

#858 tools/docker: avoid repeated installation of the libsgx-uae-service package
  tools/docker/Dockerfile-inclavare-dev-alinux2
  tools/docker/Dockerfile-inclavare-dev-centos8.2
  tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
Labels: bug, medium

#859 enclave-tls/dist: add SGX SDK compile check in the rpm spec
  enclave-tls/dist/rpm/enclave_tls.spec
Labels: enhancement, medium, testing-before-checkin

#861 enclave-tls: fix invalid response retrieved from occlum enclave-tls server
  enclave-tls/samples/enclave-tls-client/client.c
  enclave-tls/samples/enclave-tls-server/server.c
Labels: testing-before-checkin

#864 enclave-tls: provide deb spec
  enclave-tls/dist/Makefile
  enclave-tls/dist/deb/build.sh
  enclave-tls/dist/deb/debian/changelog
  enclave-tls/dist/deb/debian/compat
  enclave-tls/dist/deb/debian/control
  enclave-tls/dist/deb/debian/rules
  enclave-tls/dist/deb/debian/source/format
Labels: enhancement, medium, testing-before-checkin

#871 workflows/docker: change to use the Alibaba Cloud teesdk and protobuf 2.5.0 in the alinux2 compilation test dockerfile
  .github/workflows/docker/Dockerfile-compilation-testing-alinux2
Labels: enhancement, medium

#849 CI/CD: add test for shelter with enclave-tls-server
  .github/actions/generate-random-port/action.yml
  .github/actions/generate-random-port/generate_port.sh
  .github/workflows/pr_shelter.yml
Labels: testing-before-checkin

#869 enclave-tls: introduce LVI mitigations by default
  enclave-tls/README.md
  enclave-tls/rules/sgx_env.mk
  enclave-tls/src/external/wolfssl/Makefile
Labels: testing-before-checkin
