Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-05, with the labels that each got.

#884 skeleton/README.md: fix the URL error of intergrating skeleton with tls server
  rune/libenclave/internal/runtime/pal/skeleton/README.md
Labels: bug, documentation

#886 shelter/Makefile: support SGX SDK installed in the non-standard path
  shelter/Makefile
Labels: enhancement, medium

#888 CI/CD: add SGX and DCAP versions both in the centos and ubuntu pr tests
  .github/workflows/pr_enclave_tls.yml
  .github/workflows/pr_epm.yml
  .github/workflows/pr_shelter.yml
  .github/workflows/pr_skeleton.yml
Labels: enhancement, medium

#896 CI/CD: build and install shelter deb package failed
  shelter/dist/deb/debian/changelog
  shelter/dist/deb/debian/control
Labels: bug, enhancement

#897 skeleton/tls-server.c: fix the invalid response retrieved from enclave-tls server error
  rune/libenclave/internal/runtime/pal/skeleton/tls-server.c
Labels: bug, high

#900 shelter/README.md: fix the dependent go version error
  shelter/README.md
Labels: bug, documentation

#901 shelter/README.md: minor fixes
  shelter/README.md
Labels: bug, documentation

#906 skeleton/intergrate_skeleton_with_enclave_tls.md: add shelter as an enclave tls client support
  rune/libenclave/internal/runtime/pal/skeleton/intergrate_skeleton_with_enclave_tls.md
Labels: documentation, medium

#915 CI/CD: fix a typo
  .github/workflows/pr_skeleton.yml
Labels: bug, medium

#924 shelter: drop unnecessary sgx sdk libs dependency and can run on non-…
  shelter/remoteattestation/ratlsclient.c
  shelter/remoteattestation/securitychannel.go
Labels: enhancement, medium, testing-before-checkin

#925 shelter + skeleton + enclave-tls: remote attestation will print the m…
  shelter/remoteattestation/ratlsclient.c
Labels: testing-before-checkin

#933 shelter/remoteattestation: add -std=gnu11 CGO FLAGS to fix gcc 4.8.5 compile error in alinux2
  shelter/remoteattestation/securitychannel.go
Labels: bug, high

#932 inclavared: built-in lib search path /opt/enclave-tls
  inclavared/Makefile
  inclavared/app/src/enclave-tls.rs
  inclavared/app/src/ffi.rs
Labels: enhancement, medium

#940 enclave-tls: fix build warnings about wolfssl-sgx
  enclave-tls/src/tls_wrappers/wolfssl-sgx/ecalls.c
Labels: bug, medium, testing-before-checkin

#952 enclave-tls/samples: provide --help/-h option to show the usage
  enclave-tls/README.md
  enclave-tls/samples/enclave-tls-client/client.c
  enclave-tls/samples/enclave-tls-server/server.c
Labels: testing-before-checkin

#966 README: add nightly alinux2 and SGX2 status badge
  README.md
Labels: epic, gating, high

#963 enclave-tls/README.md: add error message description in non-sgx envir…
  enclave-tls/README.md
Labels: documentation, gating

#848 enclave-tls: add QvE support in ECDSA verification
  enclave-tls/rules/sgx_env.mk
  enclave-tls/rules/sgx_rules.mk
  enclave-tls/src/Makefile
  enclave-tls/src/crypto_wrappers/wolfcrypt/gen_cert.c
  enclave-tls/src/enclave_quotes/Makefile
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/Makefile
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/cleanup.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/collect_evidence.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/ecalls.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/init.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/main.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/ocalls.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/pre_init.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/quote_generation.h
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/sgx_ecdsa.h
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/sgx_ecdsa_qve.edl
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/verify_evidence.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa/collect_evidence.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa/verify_evidence.c
  enclave-tls/src/external/wolfssl/patch/wolfssl.patch
  enclave-tls/src/sgx/Makefile
  enclave-tls/src/tls_wrappers/wolfssl-sgx/wolfssl_sgx.edl
  enclave-tls/src/tls_wrappers/wolfssl/oid.c
  enclave-tls/src/tls_wrappers/wolfssl/un_negotiate.c
  enclave-tls/src/tls_wrappers/wolfssl/wolfssl.h
Labels: epic, gating, high, testing-before-checkin

#984 CI/CD: avoid building the shelter rpm package in the nightly centos SGX1 test
  .github/workflows/nightly-centos-sgx1.yml
Labels: bug, high

#982 inclavared: Fix the failure of calling enclcave_tls_cleanup()
  inclavared/app/src/main.rs
Labels: bug, medium, testing-before-checkin

#999 enclave-tls/dist: fix build the debuginfo rpm package failed in the centos 8.x
  enclave-tls/dist/rpm/enclave_tls.spec
Labels: bug, high

#1017 enclave-tls: add to handle for failing to load sgx stub enclave
  enclave-tls/samples/enclave-tls-client/client.c
  enclave-tls/samples/enclave-tls-server/server.c
Labels: bug, gating, high

#1025 enclave-tls: sanity check for the result of ecall into wolfssl init
  enclave-tls/src/tls_wrappers/wolfssl-sgx/init.c
Labels: bug, gating, high

#1030 enclave-tls/dist: add dh_strip --exclude rules in the deb and dbgsym packages
  enclave-tls/dist/deb/debian/rules
Labels: epic, medium

#1019 inclavared: sanity check the validation of request from shelter
  shelter/racommand.go
  shelter/remoteattestation/ratlsclient.c
  shelter/remoteattestation/securitychannel.go
  shelter/utils/manageprotocol.go
Labels: testing-before-checkin

#995 inclavared: sanity check the validation of request from shelter
  inclavared/app/Cargo.lock
  inclavared/app/Cargo.toml
  inclavared/app/build.rs
  inclavared/app/src/main.rs
Labels: epic, medium, testing-before-checkin

#1031 enclave-tls/dist: add the postun rules in the rpm spec
  enclave-tls/dist/rpm/enclave_tls.spec
Labels: enhancement, medium

#1037 inclavared: cleanup resources after tls handshake fails
  inclavared/app/src/main.rs
Labels: bug, high, testing-before-checkin

#1039 inclavared: use only one enclave for all connections
  inclavared/app/src/main.rs
Labels: bug, high, testing-before-checkin

#1036 CICD: need to change enclave-tls default path in shelter cicd yml
  .github/workflows/pr_shelter.yml
Labels: bug, medium

#1041 enclave-tls/dist: support debuginfo packages that can run enclave-tls-server/client successfully in centos 8.2
  enclave-tls/dist/rpm/enclave_tls.spec
Labels: epic, medium

#1040 enclave-tls: fix an issue about segment fault when running sgx ecdsa …
  enclave-tls/src/api/enclave_tls_init.c
  enclave-tls/src/enclave_quotes/internal/etls_enclave_quote_select.c
  enclave-tls/src/include/enclave-tls/tls_wrapper.h
  enclave-tls/src/include/internal/enclave_quote.h
  enclave-tls/src/tls_wrappers/api/tls_wrapper_verify_certificate_extension.c
  enclave-tls/src/tls_wrappers/internal/etls_tls_wrapper_select.c
  enclave-tls/src/tls_wrappers/wolfssl-sgx/ocalls.c
  enclave-tls/src/tls_wrappers/wolfssl-sgx/wolfssl_sgx.edl
  enclave-tls/src/tls_wrappers/wolfssl/negotiate.c
  enclave-tls/src/tls_wrappers/wolfssl/un_negotiate.c
Labels: bug, gating, high, testing-before-checkin

#1047 enclave-tls/README.md: supplement neccessary installation package des…
  enclave-tls/README.md
Labels: bug, gating

#1050 enclave-tls: fix build warning when make SGX=1
  enclave-tls/src/enclave_quotes/sgx-ecdsa/ecalls.c
Labels: bug, testing-before-checkin

#1045 enclave-tls: enable capability flags in the register of enclave quote instance
  enclave-tls/src/Makefile
  enclave-tls/src/crypto_wrappers/api/crypto_wrapper_register.c
  enclave-tls/src/crypto_wrappers/wolfcrypt-sgx/main.c
  enclave-tls/src/enclave_quotes/api/enclave_quote_register.c
  enclave-tls/src/enclave_quotes/internal/etls_enclave_quote_select.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/main.c
  enclave-tls/src/enclave_quotes/sgx-la/main.c
  enclave-tls/src/include/internal/sgxutils.h
  enclave-tls/src/tls_wrappers/api/tls_wrapper_register.c
  enclave-tls/src/tls_wrappers/wolfssl-sgx/main.c
  enclave-tls/src/util/sgxutils.c
Labels: enhancement, medium

#1052 enclave-tls: allow sgx_ecdsa instance to support the evidence generatd by sgx_ecdsa_qve
  enclave-tls/src/crypto_wrappers/api/crypto_wrapper_register.c
  enclave-tls/src/crypto_wrappers/internal/etls_crypto_wrapper_load_single.c
  enclave-tls/src/crypto_wrappers/internal/etls_crypto_wrapper_select.c
  enclave-tls/src/crypto_wrappers/nullcrypto/main.c
  enclave-tls/src/crypto_wrappers/wolfcrypt-sgx/main.c
  enclave-tls/src/crypto_wrappers/wolfcrypt/gen_cert.c
  enclave-tls/src/crypto_wrappers/wolfcrypt/main.c
  enclave-tls/src/enclave_quotes/api/enclave_quote_register.c
  enclave-tls/src/enclave_quotes/internal/etls_enclave_quote_load_single.c
  enclave-tls/src/enclave_quotes/internal/etls_enclave_quote_select.c
  enclave-tls/src/enclave_quotes/nullquote/main.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/main.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa/collect_evidence.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa/main.c
  enclave-tls/src/enclave_quotes/sgx-ecdsa/verify_evidence.c
  enclave-tls/src/enclave_quotes/sgx-la/main.c
  enclave-tls/src/external/wolfssl/patch/wolfssl.patch
  enclave-tls/src/include/enclave-tls/crypto_wrapper.h
  enclave-tls/src/include/enclave-tls/enclave_quote.h
  enclave-tls/src/include/enclave-tls/tls_wrapper.h
  enclave-tls/src/tls_wrappers/api/tls_wrapper_register.c
  enclave-tls/src/tls_wrappers/api/tls_wrapper_verify_certificate_extension.c
  enclave-tls/src/tls_wrappers/internal/etls_tls_wrapper_load_single.c
  enclave-tls/src/tls_wrappers/internal/etls_tls_wrapper_select.c
  enclave-tls/src/tls_wrappers/nulltls/main.c
  enclave-tls/src/tls_wrappers/wolfssl-sgx/main.c
  enclave-tls/src/tls_wrappers/wolfssl/main.c
  enclave-tls/src/tls_wrappers/wolfssl/oid.c
  enclave-tls/src/tls_wrappers/wolfssl/un_negotiate.c
  enclave-tls/src/tls_wrappers/wolfssl/wolfssl.h
Labels: testing-before-checkin

#1049 enclave-tls: auto-adapt verifier parameter and follow user parameters…
  enclave-tls/src/enclave_quotes/internal/etls_enclave_quote_select.c
  enclave-tls/src/include/enclave-tls/api.h
  enclave-tls/src/tls_wrappers/api/tls_wrapper_verify_certificate_extension.c
Labels: enhancement, gating

#1056 shelter/dist: update rpm and deb version to 0.6.1
  shelter/dist/deb/debian/changelog
  shelter/dist/rpm/shelter.spec
Labels: enhancement, medium

#1061 workflow: fix CI/CD failure due to the lack of -v nullquote
  .github/workflows/pr_enclave_tls.yml
  .github/workflows/pr_shelter.yml
Labels: bug, high

#1062 shelter/dist: fix the badly formatted trailer line warning
  shelter/dist/deb/debian/changelog
Labels: bug, medium

#1059 enclave-tls/docs: add the guide to run inclavared and shelter with enclave-tls
  enclave-tls/docs/run_inclavared_and_shelter_with_enclave_tls.md
Labels: documentation, enhancement, high

#1065 workflows/pr_enclave_tls: fix CI/CD failure due to the lack of -v enclave quote type
  .github/workflows/pr_enclave_tls.yml
Labels: bug, gating, high

#1063 enclave-tls: add enclave-tls as the stable component in top Makefile
  Makefile
Labels: testing-before-checkin

#1066 workflows/pr_epm: fix CI/CD failure due to metadata_lock.pid does not exist
  .github/workflows/pr_epm.yml
Labels: bug, medium

#1069 epm & shim: update spec files of epm and shim
  epm/dist/deb/debian/changelog
  epm/dist/rpm/epm.spec
  shim/dist/deb/debian/changelog
  shim/dist/rpm/shim-rune.spec
Labels: documentation

#1081 CI/CD: separate nullquote instance into nullattester and nullverifier…
  .github/workflows/pr_enclave_tls.yml
  .github/workflows/pr_shelter.yml
Labels: enhancement, medium
