Repository inclavare-containers/inclavare-containers, pull requests merged in 2021-03, with the labels that each got.

#666 ra-tls: fix build failure due to missing reconfiguration
  ra-tls/Makefile
Labels: bug, medium, testing-before-checkin

#670 ra-tls/Makefile: add ra-tls epid compiling dependency check for python
  ra-tls/sgx-ra-tls/Makefile
Labels: bug, high, testing-before-checkin

#671 skeleton: document well the dependency about protobuf
  rune/libenclave/internal/runtime/pal/skeleton/README.md
Labels: documentation, medium

#667 CI/CD: use yum to replace rpm to install the sgxsdk and dcap in the compile-check images
  .github/workflows/docker/Dockerfile-compile-check-centos8.1
Labels: enhancement, medium

#682 epm: fix the nil pointer bug when getting the ancestor caches
  epm/pkg/metadata/metadata.go
Labels: bug, medium, testing-before-checkin

#680 CI/CD: both enhance commit skeleton test in ubuntu18.04 and centos 8.2 of SGX2
  .github/workflows/commit_skeleton_ex.yml
Labels: enhancement, medium

#685 CI/CD: add docker tag for inclavare-dev and inclavare-test images in commit-skeleton-ex.
  .github/workflows/commit_skeleton_ex.yml
Labels: enhancement, medium

#681 CI/CD: add inclavare containers development centos8.2 and ubuntu 18.04 docker images
  .github/workflows/manually_inclavare_dev_image.yml
  tools/docker/Dockerfile-inclavare-dev-centos8.2
  tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
Labels: enhancement, medium

#689 docs/k8s: update occlum version to 0.20.0
  docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md
Labels: documentation, enhancement, testing-before-checkin

#691 epm/dist/deb && rpm: add the mkdir /var/run/epm in the post install stage
  epm/dist/deb/debian/postinst
  epm/dist/rpm/epm.spec
Labels: bug, enhancement, testing-before-checkin

#692 CI/CD: both enhance commit epm test in ubuntu 18.04 and centos 8.2 of SGX2
  .github/workflows/commit_epm_ex.yml
Labels: enhancement, medium

#694 shim & epm: adapt to version 0.21.0 of occlum
  .github/workflows/nightly-centos-sgx1.yml
  .github/workflows/nightly-ubuntu-sgx1.yml
  epm/pkg/epm/bundle-cache-pool/occlum/bundle-cache0.go
  epm/pkg/epm/bundle-cache-pool/occlum/bundle-cache1.go
  shim/runtime/carrier/constants/constants.go
  shim/runtime/carrier/occlum/config.go
Labels: testing-before-checkin

#696 CI/CD: adapte to occlum 0.21.0 with centos8.2 and ubuntu 18.04
  .github/workflows/commit_crictl.yml
  .github/workflows/commit_epm.yml
  .github/workflows/commit_occlum.yml
  .github/workflows/commit_shelter.yml
  .github/workflows/commit_skeleton.yml
  .github/workflows/docker/Dockerfile-centos8.2
  .github/workflows/docker/Dockerfile-ubuntu18.04
  .github/workflows/manually_centos_test_image.yml
  .github/workflows/manually_repository_setup.yml
Labels: epic, gating, high

#697 CI/CD: eliminate the warning of target translations are configured multiple times in kubernetes.list
  .github/workflows/nightly-ubuntu-sgx1.yml
Labels: high

#711 CI/CD: update sgx DCAP driver to version 1.41
  .github/workflows/commit_crictl.yml
  .github/workflows/commit_epm.yml
  .github/workflows/commit_occlum.yml
  .github/workflows/commit_skeleton.yml
Labels: bug, gating, high

#712 docs && CI/CD: update CentOS 8.1 to centOS 8.2 and Occlum:0.20.0 to Occlum:0.21.0
  .github/workflows/commit_compile_check.yml
  .github/workflows/docker/Dockerfile-compile-check-centos8.2
  .github/workflows/manually_compile_check_image.yml
  .github/workflows/manually_wamr_image.yml
  README.md
  docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md
  docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md
  rune/libenclave/internal/runtime/pal/skeleton/README.md
  rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
Labels: bug, gating, high, testing-before-checkin

#718 CI/CD: add rm -rf /var/run/epm in the nightly test
  .github/workflows/nightly-centos-sgx1.yml
  .github/workflows/nightly-ubuntu-sgx1.yml
Labels: bug, medium

#719 CI/CD: only test ra in the SGX1 occlum ubuntu docker images
  .github/workflows/commit_skeleton.yml
Labels: bug, gating, workaround

#720 CI/CD: rename commit_epm_ex.yml as commit_epm.yml
  .github/workflows/commit_epm.yml
  .github/workflows/commit_epm_ex.yml
Labels: enhancement, medium

#721 CI/CD: rename skeleton_commit_ex.yml as skeleton_commit.yml
  .github/workflows/commit_skeleton.yml
  .github/workflows/commit_skeleton_ex.yml
Labels: enhancement, medium

#723 shim/runtime/v2/rune: remove unused attestation package
  shim/runtime/v2/rune/v2/attestation/attestation.go
  shim/runtime/v2/rune/v2/attestation/utils.go
Labels: enhancement, medium, testing-before-checkin

#727 CI/CD: support compile check on alinux2 system
  .github/workflows/commit_compile_check.yml
  .github/workflows/docker/Dockerfile-compile-check-alinux2
  .github/workflows/manually_compile_check_image.yml
Labels: enhancement, epic, gating

#732 CI/CD: add alinux2 commit epm test
  .github/workflows/commit_epm.yml
Labels: enhancement, medium

#733 CI/CD: add clean up jobs in commit skeleton test
  .github/workflows/commit_skeleton.yml
Labels: bug, medium

#734 enclave-tls: add wolfssl sgx support in tls wrapper
  enclave-tls/samples/enclave-tls-client/Makefile
  enclave-tls/samples/enclave-tls-client/ra-tls-client.c
  enclave-tls/samples/enclave-tls-server/ra-tls-server.c
  enclave-tls/samples/enclave-tls-server/run.go
  enclave-tls/src/Makefile
  enclave-tls/src/external/Makefile
  enclave-tls/src/external/patch/wolfssl.patch
  enclave-tls/src/include/enclave-tls/api.h
  enclave-tls/src/include/enclave-tls/log.h
  enclave-tls/src/include/enclave-tls/tls_wrapper.h
  enclave-tls/src/include/internal/enclave_quote.h
  enclave-tls/src/lib/api/enclave_tls_init.c
  enclave-tls/src/lib/core/etls_core_generate_certificate.c
  enclave-tls/src/lib/tls_wrappers/api/tls_wrapper_verify_certificate_extension.c
  enclave-tls/src/lib/tls_wrappers/internal/etls_tls_wrapper_select.c
  enclave-tls/src/lib/tls_wrappers/null/init.c
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/Makefile
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/app.c
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/app.h
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/main.c
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/wolfssl-enclave/Makefile
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/wolfssl-enclave/wolfssl_enclave.c
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/wolfssl-enclave/wolfssl_enclave.config.xml
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/wolfssl-enclave/wolfssl_enclave.edl
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/wolfssl-enclave/wolfssl_enclave.h
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/wolfssl-enclave/wolfssl_enclave.lds
  enclave-tls/src/lib/tls_wrappers/wolfssl-sgx/wolfssl-enclave/wolfssl_enclave_private.pem
  enclave-tls/src/lib/tls_wrappers/wolfssl/cleanup.c
  enclave-tls/src/lib/tls_wrappers/wolfssl/init.c
  enclave-tls/src/lib/tls_wrappers/wolfssl/negotiate.c
  enclave-tls/src/lib/tls_wrappers/wolfssl/receive.c
  enclave-tls/src/lib/tls_wrappers/wolfssl/transmit.c
  enclave-tls/src/lib/tls_wrappers/wolfssl/un_negotiate.c
  enclave-tls/src/lib/tls_wrappers/wolfssl/use_cert.c
  enclave-tls/src/lib/tls_wrappers/wolfssl/use_privkey.c
Labels: enhancement, epic, rfc

#738 CI/CD: add alinux2 commit skeleton test
  .github/workflows/commit_skeleton.yml
Labels: enhancement, medium

#739 CI/CD: add alinux2 commit occlum test
  .github/workflows/commit_occlum.yml
Labels: enhancement, medium

#744 nightly ubuntu: Specify the version of the sgx and dcap packages
  .github/workflows/nightly-ubuntu-sgx1.yml
Labels: enhancement, high
